language: python
stages:
- code-quality
- tests
cache: pip
jobs:
  include:
  - stage: code-quality
    python: '3.6'
    install: pip install flake8
    script: flake8

  - stage: tests
    python: '3.6'
    before_install:
    - pip install pytest pytest-cov
    install:
    - python setup.py install
    script:
    - PYTORCH_JIT=0 pytest --cov dropblock --cov-report term-missing -v tests/

  - stage: tests
    python: '3.6'
    before_install:
    - pip install pytest
    install:
    - python setup.py install
    script:
    - PYTORCH_JIT=1 pytest -v tests/
